In [1]:
import pandas as pd

# read data

In [2]:
roberta_df = pd.read_csv("tom_scott_copyright_sentiment_roberta.csv")
roberta_df.head(5)

,id,roberta_neg,roberta_neu,roberta_pos,snippet.textOrginal,snippet.likeCount,snippet.publishedAt
0,UgzzkGXp9OqcNTIfg8N4AaABAg,0.001375,0.111756,0.886869,"Yep, 42 minutes of video. This was a big proje...",29165,2020-03-14T14:07:53Z
1,UgxHwgzeFMX03Ls9YoJ4AaABAg,0.573469,0.400585,0.025947,"Would like to see a follow-up on this take, no...",0,2023-09-21T19:24:12Z
2,UgyHNNyAj-FS9Ja1rSt4AaABAg,0.012195,0.274506,0.713300,"""The UK has one of the world's friendliest cop...",1,2023-09-21T17:01:28Z
3,Ugz2llq0yWm-fPYxguJ4AaABAg,0.162383,0.699381,0.138236,My take on the whole giphy being transformativ...,1,2023-09-19T15:18:44Z
4,UgyOKH4bXfPQ9zKU06t4AaABAg,0.624730,0.360903,0.014367,"""Fact checking"" is a modern euphemism for cens...",0,2023-09-18T15:37:31Z

In [4]:
vader_df = pd.read_csv('tom_scott_copyright_sentiment_vader.csv')
vader_df.head(5)

,id,vader_neg,vader_neu,vader_pos,vader_compound,snippet.textOrginal,snippet.likeCount,snippet.publishedAt
0,UgzzkGXp9OqcNTIfg8N4AaABAg,0.000,0.858,0.142,0.5848,"Yep, 42 minutes of video. This was a big proje...",29165,2020-03-14T14:07:53Z
1,UgxHwgzeFMX03Ls9YoJ4AaABAg,0.000,0.898,0.102,0.3612,"Would like to see a follow-up on this take, no...",0,2023-09-21T19:24:12Z
2,UgyHNNyAj-FS9Ja1rSt4AaABAg,0.000,0.833,0.167,0.5574,"""The UK has one of the world's friendliest cop...",1,2023-09-21T17:01:28Z
3,Ugz2llq0yWm-fPYxguJ4AaABAg,0.038,0.928,0.034,0.1406,My take on the whole giphy being transformativ...,1,2023-09-19T15:18:44Z
4,UgyOKH4bXfPQ9zKU06t4AaABAg,0.000,1.000,0.000,0.0000,"""Fact checking"" is a modern euphemism for cens...",0,2023-09-18T15:37:31Z

## combine data together

In [12]:
vader_scores = vader_df[['vader_neg','vader_neu','vader_pos','vader_compound']]
vader_scores.head()

   vader_neg  vader_neu  vader_pos  vader_compound
0      0.000      0.858      0.142          0.5848
1      0.000      0.898      0.102          0.3612
2      0.000      0.833      0.167          0.5574
3      0.038      0.928      0.034          0.1406
4      0.000      1.000      0.000          0.0000

In [16]:
compiled_data = roberta_df[["snippet.textOrginal"]]
compiled_data = pd.concat([compiled_data, roberta_df[["roberta_neg","roberta_neu","roberta_pos"]], vader_scores], axis=1)
compiled_data.head()

,snippet.textOrginal,roberta_neg,roberta_neu,roberta_pos,vader_neg,vader_neu,vader_pos,vader_compound
0,"Yep, 42 minutes of video. This was a big proje...",0.001375,0.111756,0.886869,0.000,0.858,0.142,0.5848
1,"Would like to see a follow-up on this take, no...",0.573469,0.400585,0.025947,0.000,0.898,0.102,0.3612
2,"""The UK has one of the world's friendliest cop...",0.012195,0.274506,0.713300,0.000,0.833,0.167,0.5574
3,My take on the whole giphy being transformativ...,0.162383,0.699381,0.138236,0.038,0.928,0.034,0.1406
4,"""Fact checking"" is a modern euphemism for cens...",0.624730,0.360903,0.014367,0.000,1.000,0.000,0.0000

# sort data

In [22]:
roberta_sorted = compiled_data.query('roberta_neg > 0.5').sort_values('roberta_neg', ascending=False).reset_index(drop=True)
roberta_sorted.to_csv("sorted_by_roberta.csv", index=False)
roberta_sorted.head(5)

,snippet.textOrginal,roberta_neg,roberta_neu,roberta_pos,vader_neg,vader_neu,vader_pos,vader_compound
0,the world is extremely broken and WRONG becaus...,0.983424,0.014245,0.002331,0.000,0.715,0.285,0.7488
1,I hope I never get recommended this channel ag...,0.982802,0.014779,0.002419,0.000,1.000,0.000,0.0000
2,"Memories is so annoying, it is so repetitive a...",0.981988,0.015313,0.002699,0.000,0.702,0.298,0.6249
3,Copyright is a horrible word that kills my wee...,0.981498,0.015958,0.002544,0.163,0.767,0.070,-0.4215
4,"DAMN! i hate the world, can we delete it?",0.980934,0.015734,0.003332,0.090,0.633,0.277,0.8824

In [23]:
vader_sorted = compiled_data.query('vader_compound < -0.5').sort_values('vader_compound').reset_index(drop=True)
vader_sorted.to_csv("sorted_by_vader.csv", index=False)
vader_sorted.head(5)

,snippet.textOrginal,roberta_neg,roberta_neu,roberta_pos,vader_neg,vader_neu,vader_pos,vader_compound
0,So..... if I were to stream/upload me playing ...,0.307286,0.569230,0.123483,0.158,0.736,0.106,-0.9940
1,"I'm just paranoid that anything I do, could be...",0.871028,0.119296,0.009676,0.156,0.784,0.060,-0.9905
2,"""Horrible gamer children"" is my new favorite p...",0.538637,0.252877,0.208486,0.360,0.640,0.000,-0.9904
3,THANK YOU.,0.008510,0.123658,0.867832,0.184,0.773,0.042,-0.9861
4,yet there are still no ads on the vid...,0.426379,0.539638,0.033983,0.180,0.820,0.000,-0.9835